// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://catongwvgzqavnuhdjwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdG9uZ3d2Z3pxYXZudWhkand6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODMyMDMsImV4cCI6MjA2ODk1OTIwM30._uojjZx6iKE6cqkkjsSfsXhbrWSRBmAoTgbOHH7phrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});